include utils.mk

this:=$(call get-my-dir)

all: true_all

BIN?=bin

include $(this)/build.mk

include $(this)/carryall-library-requirements.mk

CARRYALL_LIBRARY_DYN_NAME:=libcarryall.so
CARRYALL_LIBRARY_DYN_TARGET:=$(CARRYALL_LIBRARY_DYN_NAME:%.so=%)

CARRYALL_LIBRARY_DYN_SRCS:=\
  $(CARRYALL_LIBRARY_SRCS)\

CARRYALL_LIBRARY_DYN_INCLUDE_DIRECTORIES:=\
  $(CARRYALL_LIBRARY_INCLUDE_DIRECTORIES)\

CARRYALL_LIBRARY_DYN_INCLUDE_FILES:=\
  $(CARRYALL_LIBRARY_INCLUDE_FILES)\

CARRYALL_LIBRARY_DYN_CFLAGS:=\
  $(CARRYALL_LIBRARY_CFLAGS)\

CARRYALL_LIBRARY_DYN_LDFLAGS:=\
  $(CARRYALL_LIBRARY_LDFLAGS)\

CARRYALL_LIBRARY_DYN_OBJS:=\
  $(CARRYALL_LIBRARY_DYN_SRCS:%=$(BIN)/%.o)

$(BIN)/$(CARRYALL_LIBRARY_DYN_NAME):\
  $(CARRYALL_LIBRARY_DYN_OBJS)

$(CARRYALL_LIBRARY_DYN_TARGET): CFLAGS+=$(CARRYALL_LIBRARY_DYN_CFLAGS)
$(CARRYALL_LIBRARY_DYN_TARGET): LDFLAGS+=$(CARRYALL_LIBRARY_DYN_LDFLAGS)
$(CARRYALL_LIBRARY_DYN_TARGET): INCLUDE_DIRECTORIES+=$(CARRYALL_LIBRARY_DYN_INCLUDE_DIRECTORIES:%=-I%)
$(CARRYALL_LIBRARY_DYN_TARGET): INCLUDE_FILES+=$(CARRYALL_LIBRARY_DYN_INCLUDE_FILES:%=-include %)
$(CARRYALL_LIBRARY_DYN_TARGET): MAJOR:=$(CARRYALL_LIBRARY_DYN_MAJOR)
$(CARRYALL_LIBRARY_DYN_TARGET): VERSION:=$(CARRYALL_LIBRARY_DYN_MAJOR).$(CARRYALL_LIBRARY_DYN_MINOR).$(CARRYALL_LIBRARY_DYN_STEP)
$(CARRYALL_LIBRARY_DYN_TARGET): $(BIN)/$(CARRYALL_LIBRARY_DYN_NAME)

.PHONY: $(CARRYALL_LIBRARY_DYN_TARGET)
  TARGETS+=$(CARRYALL_LIBRARY_DYN_TARGET)

include $(this)/carryall-tester-requirements.mk

CARRYALL_TESTER_APP_NAME:=carryall-tester.exe
CARRYALL_TESTER_APP_TARGET:=$(CARRYALL_TESTER_APP_NAME:%.exe=%)

CARRYALL_TESTER_APP_SRCS:=\
  $(CARRYALL_TESTER_SRCS)\

CARRYALL_TESTER_APP_INCLUDE_DIRECTORIES:=\
  $(CARRYALL_TESTER_INCLUDE_DIRECTORIES)\

CARRYALL_TESTER_APP_INCLUDE_FILES:=\
  $(CARRYALL_TESTER_INCLUDE_FILES)\

CARRYALL_TESTER_APP_CFLAGS:=\
  $(CARRYALL_TESTER_CFLAGS)\

CARRYALL_TESTER_APP_LDFLAGS:=\
  $(CARRYALL_TESTER_LDFLAGS)\

CARRYALL_TESTER_APP_OBJS:=\
  $(CARRYALL_TESTER_APP_SRCS:%=$(BIN)/%.o)\

$(BIN)/$(CARRYALL_TESTER_APP_NAME):\
  $(CARRYALL_TESTER_APP_OBJS)

$(CARRYALL_TESTER_APP_TARGET): CFLAGS+=$(CARRYALL_TESTER_APP_CFLAGS)
$(CARRYALL_TESTER_APP_TARGET): LDFLAGS+=$(CARRYALL_TESTER_APP_LDFLAGS)
$(CARRYALL_TESTER_APP_TARGET): INCLUDE_DIRECTORIES+=$(CARRYALL_TESTER_APP_INCLUDE_DIRECTORIES:%=-I%)
$(CARRYALL_TESTER_APP_TARGET): INCLUDE_FILES+=$(CARRYALL_TESTER_APP_INCLUDE_FILES:%=-include %)
$(CARRYALL_TESTER_APP_TARGET): $(BIN)/$(CARRYALL_TESTER_APP_NAME)

.PHONY: $(CARRYALL_TESTER_APP_TARGET)
  TARGETS+=$(CARRYALL_TESTER_APP_TARGET)

include $(this)/carryall-fuzzer-requirements.mk

CARRYALL_FUZZER_APP_NAME:=carryall-fuzzer.exe
CARRYALL_FUZZER_APP_TARGET:=$(CARRYALL_FUZZER_APP_NAME:%.exe=%)

CARRYALL_FUZZER_APP_SRCS:=\
  $(CARRYALL_FUZZER_SRCS)\

CARRYALL_FUZZER_APP_INCLUDE_DIRECTORIES:=\
  $(CARRYALL_FUZZER_INCLUDE_DIRECTORIES)\

CARRYALL_FUZZER_APP_INCLUDE_FILES:=\
  $(CARRYALL_FUZZER_INCLUDE_FILES)\

CARRYALL_FUZZER_APP_CFLAGS:=\
  $(CARRYALL_FUZZER_CFLAGS)\

CARRYALL_FUZZER_APP_LDFLAGS:=\
  $(CARRYALL_FUZZER_LDFLAGS)\

CARRYALL_FUZZER_APP_OBJS:=\
  $(CARRYALL_FUZZER_APP_SRCS:%=$(BIN)/%.o)\

$(BIN)/$(CARRYALL_FUZZER_APP_NAME):\
  $(CARRYALL_FUZZER_APP_OBJS)\

$(CARRYALL_FUZZER_APP_TARGET): CFLAGS+=$(CARRYALL_FUZZER_APP_CFLAGS)
$(CARRYALL_FUZZER_APP_TARGET): LDFLAGS+=$(CARRYALL_FUZZER_APP_LDFLAGS)
$(CARRYALL_FUZZER_APP_TARGET): INCLUDE_DIRECTORIES+=$(CARRYALL_FUZZER_APP_INCLUDE_DIRECTORIES:%=-I%)
$(CARRYALL_FUZZER_APP_TARGET): INCLUDE_FILES+=$(CARRYALL_FUZZER_APP_INCLUDE_FILES:%=-include %)
$(CARRYALL_FUZZER_APP_TARGET): $(BIN)/$(CARRYALL_FUZZER_APP_NAME)

.PHONY: $(CARRYALL_FUZZER_APP_TARGET)
  TARGETS+=$(CARRYALL_FUZZER_APP_TARGET)

true_all: $(TARGETS)
