include utils.mk

this:=$(call get-my-dir)

all: true_all

BIN?=bin

include $(this)/build.mk

include $(this)/carryall-tester-requirements.mk

CARRYALL_TESTER_APP_NAME:=carryall-tester.exe
CARRYALL_TESTER_APP_TARGET:=$(CARRYALL_TESTER_APP_NAME:%.exe=%)

CARRYALL_TESTER_APP_SRCS:=\
  $(CARRYALL_TESTER_SRCS)\
  $(this)/tests/example.cpp\

CARRYALL_TESTER_APP_INCLUDE_DIRECTORIES:=\
  $(CARRYALL_TESTER_INCLUDE_DIRECTORIES)\

CARRYALL_TESTER_APP_INCLUDE_FILES:=\
  $(CARRYALL_TESTER_INCLUDE_FILES)\

CARRYALL_TESTER_APP_CFLAGS:=\
  $(CARRYALL_TESTER_CFLAGS)\
  -Wall\
  -Wextra\
  -Werror\
  -pedantic-errors\

CARRYALL_TESTER_APP_LDFLAGS:=\
  $(CARRYALL_TESTER_LDFLAGS)\

CARRYALL_TESTER_APP_OBJS:=\
  $(CARRYALL_TESTER_APP_SRCS:%=$(BIN)/%.o)

$(BIN)/$(CARRYALL_TESTER_APP_NAME):\
  $(CARRYALL_TESTER_APP_OBJS)

$(CARRYALL_TESTER_APP_TARGET): CFLAGS+=$(CARRYALL_TESTER_APP_CFLAGS)
$(CARRYALL_TESTER_APP_TARGET): LDFLAGS+=$(CARRYALL_TESTER_APP_LDFLAGS)
$(CARRYALL_TESTER_APP_TARGET): INCLUDE_DIRECTORIES+=$(CARRYALL_TESTER_APP_INCLUDE_DIRECTORIES)
$(CARRYALL_TESTER_APP_TARGET): INCLUDE_FILES+=$(CARRYALL_TESTER_APP_INCLUDE_FILES)
$(CARRYALL_TESTER_APP_TARGET): $(BIN)/$(CARRYALL_TESTER_APP_NAME)

.PHONY: $(CARRYALL_TESTER_APP_TARGET)
  TARGETS+=$(CARRYALL_TESTER_APP_TARGET)

include $(this)/carryall-fuzzer-requirements.mk

CARRYALL_FUZZER_APP_NAME:=carryall-fuzzer.exe
CARRYALL_FUZZER_APP_TARGET:=$(CARRYALL_FUZZER_APP_NAME:%.exe=%)

CARRYALL_FUZZER_APP_SRCS:=\
  $(CARRYALL_FUZZER_SRCS)\
  $(this)/tests/example.cpp\

CARRYALL_FUZZER_APP_INCLUDE_DIRECTORIES:=\
  $(CARRYALL_FUZZER_INCLUDE_DIRECTORIES)\

CARRYALL_FUZZER_APP_INCLUDE_FILES:=\
  $(CARRYALL_FUZZER_INCLUDE_FILES)\

CARRYALL_FUZZER_APP_CFLAGS:=\
  $(CARRYALL_FUZZER_CFLAGS)\
  -Wall\
  -Wextra\
  -Werror\
  -pedantic-errors\

CARRYALL_FUZZER_APP_LDFLAGS:=\
  $(CARRYALL_FUZZER_LDFLAGS)\

CARRYALL_FUZZER_APP_OBJS:=\
  $(CARRYALL_FUZZER_APP_SRCS:%=$(BIN)/%.o)

$(BIN)/$(CARRYALL_FUZZER_APP_NAME):\
  $(CARRYALL_FUZZER_APP_OBJS)

$(CARRYALL_FUZZER_APP_TARGET): CFLAGS+=$(CARRYALL_FUZZER_APP_CFLAGS)
$(CARRYALL_FUZZER_APP_TARGET): LDFLAGS+=$(CARRYALL_FUZZER_APP_LDFLAGS)
$(CARRYALL_FUZZER_APP_TARGET): INCLUDE_DIRECTORIES+=$(CARRYALL_FUZZER_APP_INCLUDE_DIRECTORIES)
$(CARRYALL_FUZZER_APP_TARGET): INCLUDE_FILES+=$(CARRYALL_FUZZER_APP_INCLUDE_FILES)
$(CARRYALL_FUZZER_APP_TARGET): $(BIN)/$(CARRYALL_FUZZER_APP_NAME)

.PHONY: $(CARRYALL_FUZZER_APP_TARGET)
  TARGETS+=$(CARRYALL_FUZZER_APP_TARGET)

true_all: $(TARGETS)
